spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: lxt19981025

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lxt.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: ./easypan.log
